name: Fork Dev Build

on:
  push:
    branches:
      - sparkison
    paths-ignore:
      - '*.md'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'docs/**'

concurrency:
  group: fork-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/test-backend.yml

  frontend-tests:
    name: "Frontend Tests"
    uses: ./.github/workflows/test-frontend.yml

  build-package:
    name: Build Package
    uses: ./.github/workflows/build-package.yml
    with:
      tag: dev

  publish:
    name: Build and Push Dev Image
    if: github.repository == 'sparkison/mealie'
    needs:
      - frontend-tests
      - backend-tests
      - build-package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Retrieve Python package
        uses: actions/download-artifact@v6
        with:
          name: backend-dist
          path: dist

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          build-contexts: |
            packages=dist
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:dev
          build-args: |
            COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
